version: '3.8'

services:
  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    container_name: namenode
    hostname: namenode
    ports:
      - "9870:9870"  # Web UI Hadoop (NameNode)
      - "9000:9000"  # HDFS RPC endpoint (fs.defaultFS = hdfs://namenode:9000)
    environment:
      - CLUSTER_NAME=test
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
    volumes:
      - ./hadoop-namenode:/hadoop-data
    networks:
      - hadoop

  datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode
    hostname: datanode
    depends_on:
      - namenode
    environment:
      - SERVICE_NAME=datanode
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
    volumes:
      - ./hadoop-datanode:/hadoop-data
    networks:
      - hadoop

  spark-master:
    image: bde2020/spark-master:3.1.2-hadoop3.2
    container_name: spark-master
    ports:
      - "8080:8080"  # MasterWebUI
      - "7077:7077"  # Spark worker communication
      - "4040:4040" # SparkUI
    environment:
      - SPARK_MASTER_HOST=spark-master
      - SPARK_MASTER_PORT=7077
      - SPARK_PUBLIC_DNS=localhost  # можно поменять, если нужен внешний доступ
      - HADOOP_CORE_CONF_fs_defaultFS=hdfs://namenode:9000
    volumes:
      - ./spark-data:/opt/spark/work  # рабочая директория для Spark
    depends_on:
      - namenode
    networks:
      - hadoop

  spark-worker:
    image: bde2020/spark-worker:3.1.2-hadoop3.2
    container_name: spark-worker
    ports:
      - "8081:8081"  # WorkerUI
    depends_on:
      - spark-master
    environment:
      - SPARK_MASTER=spark://spark-master:7077
      - SPARK_WORKER_CORES=1
      - SPARK_WORKER_MEMORY=1g
    volumes:
      - ./spark-data:/opt/spark/work
    networks:
      - hadoop

  zookeeper:
    image: confluentinc/cp-zookeeper:6.2.1
    container_name: zookeeper
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
    networks:
      - hadoop

  kafka:
    image: confluentinc/cp-kafka:6.2.1
    container_name: kafka
    ports:
      - "9092:9092"  # Внешнее подключение (с хоста)
      - "9093:9093"  # Внутреннее подключение (межконтейнерное)
    depends_on:
      - zookeeper
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9093,PLAINTEXT_EXTERNAL://0.0.0.0:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9093,PLAINTEXT_EXTERNAL://localhost:9092
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_EXTERNAL:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
    networks:
      - hadoop

  flink-jobmanager:
    image: flink:1.17.1-scala_2.12-java11
    container_name: flink-jobmanager
    ports:
      - "8082:8082"  # Flink Web UI
      - "6123:6123"  # RPC
    command: jobmanager
    environment:
      - JOB_MANAGER_RPC_ADDRESS=flink-jobmanager
      - TASK_MANAGER_NUMBER_OF_TASK_SLOTS=1
      - STATE_BACKEND=filesystem
      - STATE_CHECKPOINTS_DIR=hdfs://namenode:9000/flink/checkpoints
      - STATE_SAVEPOINTS_DIR=hdfs://namenode:9000/flink/savepoints
      - FS_DEFAULT_SCHEME=hdfs://namenode:9000
    volumes:
      - ./flink-data:/opt/flink/data
    depends_on:
      - kafka
    networks:
      - hadoop

  flink-taskmanager-1:
    image: flink:1.17.1-scala_2.12-java11
    container_name: flink-taskmanager-1
    command: taskmanager
    environment:
      - JOB_MANAGER_RPC_ADDRESS=flink-jobmanager
      - TASK_MANAGER_NUMBER_OF_TASK_SLOTS=1
      - STATE_BACKEND=filesystem
      - STATE_CHECKPOINTS_DIR=hdfs://namenode:9000/flink/checkpoints
      - STATE_SAVEPOINTS_DIR=hdfs://namenode:9000/flink/savepoints
      - FS_DEFAULT_SCHEME=hdfs://namenode:9000
    volumes:
      - ./flink-data:/opt/flink/data
    depends_on:
      - flink-jobmanager
    networks:
      - hadoop

  flink-taskmanager-2:
    image: flink:1.17.1-scala_2.12-java11
    container_name: flink-taskmanager-2
    command: taskmanager
    environment:
      - JOB_MANAGER_RPC_ADDRESS=flink-jobmanager
      - TASK_MANAGER_NUMBER_OF_TASK_SLOTS=1
      - STATE_BACKEND=filesystem
      - STATE_CHECKPOINTS_DIR=hdfs://namenode:9000/flink/checkpoints
      - STATE_SAVEPOINTS_DIR=hdfs://namenode:9000/flink/savepoints
      - FS_DEFAULT_SCHEME=hdfs://namenode:9000
    volumes:
      - ./flink-data:/opt/flink/data
    depends_on:
      - flink-jobmanager
    networks:
      - hadoop

networks:
  hadoop:
    driver: bridge